spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/flashcards
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update

  messages:
    encoding: UTF-8
  thymeleaf:
    encoding: UTF-8