spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/flashcards

  jpa:
    hibernate:
      ddl-auto: update